### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by ugjka** [ugjka/wschat#1]
panic: concurrent write to websocket connection

goroutine 40 [running]:
panic(0x55b72c5662e0, 0xc4201e2ca0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/gorilla/websocket.(*Conn).flushFrame(0xc42001a780, 0x1, 0x0, 0x0, 0x0, 0xc4201fa630, 0xc4201fa654)
        /home/ugjka/goworks/src/github.com/gorilla/websocket/conn.go:504 +0x45e
github.com/gorilla/websocket.(*messageWriter).Close(0xc4201dc158, 0x55b72c57f780, 0xc4202ca330)
        /home/ugjka/goworks/src/github.com/gorilla/websocket/conn.go:627 +0x71
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc42001a780, 0x55b72c57f780, 0xc4202ca330, 0x5, 0xc42024ad88)
        /home/ugjka/goworks/src/github.com/gorilla/websocket/json.go:27 +0x112
main.user.func1.2(0xc42001a780, 0xc4202c6538, 0x5, 0xc4202c84e0)
        /home/ugjka/goworks/src/github.com/ugjka/wschat/handler.go:110 +0xa5
created by main.user.func1
        /home/ugjka/goworks/src/github.com/ugjka/wschat/handler.go:115 +0x4ea
exit status 2

**Comment by ugjka** [comment]
cc12d0053c2f74fc60dc50ba4b00f5ba8271af2d
